# A unique identifier for the head node and workers of this cluster.
cluster_name: mlopsteam50

# Cloud-provider specific configuration.
provider:
    type: gcp
    region: us-west1
    availability_zone: us-west1-a
    project_id: daring-pilot-403921

auth:
    ssh_user: ubuntu

available_node_types:
    ray_worker_small:
        # The minimum number of worker nodes of this type to launch.
        # This number should be >= 0.
        min_workers: 0
        # The maximum number of worker nodes of this type to launch.
        # This takes precedence over min_workers.
        max_workers: 2
        # The resources provided by this node type.
        resources: {"GPU": 4}
